(define (problem basicProblem1)
    (:domain redflix)
    (:objects c1 - Content c2 - Content c3 - Content d1 - Day d2 - Day d3 - Day)
    (:init
        (predecessor c2 c1)
        (predecessor c3 c1)
        (= (predecessorsToAsign c1) 2)
        (= (predecessorsToAsign c2) 0)
        (= (predecessorsToAsign c3) 0)
        (= (numDay d1) 0)
        (= (numDay d2) 1)
        (= (numDay d3) 2)
        (= (minDay c1) -1)
        (= (minDay c2) -1)
        (= (minDay c3) -1)
    )
    (:goal (forall (?content - Content) (asignedContent ?content)))
)