(define (problem basicProblem1)
(:domain redflix)
(:objects c0 - Content c1 - Content c2 - Content c3 - Content c4 - Content c5 - Content c6 - Content c7 - Content d0 - Day d1 - Day d2 - Day d3 - Day d4 - Day d5 - Day d6 - Day d7 - Day)
(:init
	(predecessor c5 c3)
	(predecessor c7 c6)
	(predecessor c2 c0)
	(predecessor c6 c0)
	(predecessor c5 c6)
	(= (numDay d0) 0)
	(= (numDay d1) 1)
	(= (numDay d2) 2)
	(= (numDay d3) 3)
	(= (numDay d4) 4)
	(= (numDay d5) 5)
	(= (numDay d6) 6)
	(= (numDay d7) 7)
)
 (:goal (forall (?content - Content) (asignedContent ?content)))
)
